## Manage versions with `nvchecker` command

## Run `nvchecker -c nvchecker.toml` to generate `new_ver.txt` file.
## Run `nvcmp -c nvchecker.toml` to see possible upgrades.
## Run `nvtake -c nvchecker.toml package` to bump the package version.


[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[curl]
## https://hub.docker.com/r/curlimages/curl/tags
## https://github.com/curl/curl/releases
source = "container"
container = "curlimages/curl"
include_regex = "\\d+\\.\\d+\\.\\d+"

[kaniko]
## https://github.com/GoogleContainerTools/kaniko/releases
## https://github.com/GoogleContainerTools/kaniko/blob/master/CHANGELOG.md
source = "github"
github = "GoogleContainerTools/kaniko"
use_max_tag = true
include_regex = "v\\d+\\.\\d+\\.\\d+$"
prefix = "v"

[node]
## https://hub.docker.com/_/node?tab=tags
## https://github.com/nodejs/node/releases
source = "container"
container = "library/node"
include_regex = "14\\.\\d+\\.\\d+-bullseye-slim"
from_pattern = "(.*)-bullseye-slim"
to_pattern = "\\1"
