export enum EGameLinks {
  fiesta = 'https://fiesta.gamigo.com',
  lastChaos = 'https://lastchaos.gamigo.com',
  echoOfSoulPhoenix = 'https://echoofsoulphoenix.aeriagames.com/',
  desertOperations = 'https://desertoperations.gamigo.com/',
  warGame1942 = 'https://wargame1942.gamigo.com/',
  auraKingdom = 'https://aurakingdom.aeriagames.com/',
  grandFantasia = 'https://grandfantasia.aeriagames.com/',
  wolfTeam = 'https://wolfteam.aeriagames.com/',
  archeage = 'https://www.trionworlds.com/archeage/',
  archeageUnchained = 'https://archeageunchained.com/',
  trove = 'https://www.trionworlds.com/trove/',
  rift = 'https://www.trionworlds.com/rift/',
  shaiya = 'https://shaiya.aeriagames.com/',
}
